files:
  - source: "/layout/Library/Application Support/Gonerino.bundle/en.lproj/Localizable.strings"
    translation: "/layout/Library/Application Support/Gonerino.bundle/%osx_code%.lproj/Localizable.strings"
