#import "Localization.h"

static NSDictionary *TranslationsForLanguage(NSString *language) {
    if ([language hasPrefix:@"tr"]) {
        return @{
            @"Block channel": @"Kanalı engelle",
            @"Block video": @"Videoyu engelle",
            @"Could not read the channel for this video": @"Bu video için kanal okunamadı",
            @"Could not read a valid channel for this video": @"Bu video için geçerli bir kanal okunamadı",
            @"Blocked %@": @"%@ engellendi",
            @"Could not block this channel": @"Bu kanal engellenemedi",
            @"Could not read the video for this item": @"Bu öğenin videosu okunamadı",
            @"Blocked video: %@": @"Engellenen video: %@",
            @"Could not block this video": @"Bu video engellenemedi",
            @"Filtering": @"Filtreleme",
            @"Blocked Content": @"Engellenen İçerik",
            @"Settings": @"Ayarlar",
            @"Gonerino": @"Gonerino",
            @"Manage filtering, block lists, import/export, and support": @"Filtrelemeyi, engelleme listelerini, içe/dışa aktarmayı ve desteği yönet",
            @"About": @"Hakkında",
            @"Enable Gonerino": @"Gonerino'yu etkinleştir",
            @"Show Gonerino Button": @"Gonerino düğmesini göster",
            @"Block 'People also watched'": @"\"Bunu izleyenler şunları da izledi\"yi engelle",
            @"Block 'You might also like'": @"\"Bunları da beğenebilirsin\"i engelle",
            @"Remove blocked content from YouTube feeds": @"Engellenen içerikleri YouTube akışlarından kaldır",
            @"Display the quick toggle in the top navigation bar": @"Hızlı geçişi üst gezinme çubuğunda göster",
            @"Remove this recommendation section": @"Bu öneri bölümünü kaldır",
            @"Channels": @"Kanallar",
            @"Videos": @"Videolar",
            @"Words": @"Kelimeler",
            @"blocked channel": @"engellenen kanal",
            @"blocked channels": @"engellenen kanal",
            @"blocked video": @"engellenen video",
            @"blocked videos": @"engellenen video",
            @"blocked word": @"engellenen kelime",
            @"blocked words": @"engellenen kelime",
            @"Save your block lists and preferences": @"Engelleme listelerini ve tercihleri kaydet",
            @"Restore your block lists and preferences": @"Engelleme listelerini ve tercihleri geri yükle",
            @"View source code and report issues": @"Kaynak kodunu görüntüle ve sorun bildir",
            @"Support Gonerino development": @"Gonerino geliştirmesini destekle",
            @"Blocked Channels": @"Engellenen Kanallar",
            @"Search channels": @"Kanallarda ara",
            @"Add Channel": @"Kanal ekle",
            @"Block a new channel": @"Yeni bir kanalı engelle",
            @"Enter the channel name to block": @"Engellenecek kanal adını girin",
            @"Channel Name": @"Kanal adı",
            @"Add": @"Ekle",
            @"Cancel": @"İptal",
            @"Delete Channel": @"Kanalı sil",
            @"Are you sure you want to delete '%@'?": @"'%@' silinsin mi?",
            @"Delete": @"Sil",
            @"Blocked Videos": @"Engellenen Videolar",
            @"Search videos": @"Videolarda ara",
            @"No blocked videos": @"Engellenen video yok",
            @"Unknown Channel": @"Bilinmeyen kanal",
            @"Delete Video": @"Videoyu sil",
            @"Blocked Words": @"Engellenen Kelimeler",
            @"Search words": @"Kelimelerde ara",
            @"Add Word": @"Kelime ekle",
            @"Block a new word or phrase": @"Yeni bir kelime veya ifadeyi engelle",
            @"Enter a word or phrase to block": @"Engellenecek kelime veya ifadeyi girin",
            @"Word or phrase": @"Kelime veya ifade",
            @"Delete Word": @"Kelimeyi sil",
            @"Export Settings": @"Ayarları dışa aktar",
            @"Import Settings": @"Ayarları içe aktar",
            @"Could not create settings file": @"Ayar dosyası oluşturulamadı",
            @"Settings exported successfully": @"Ayarlar başarıyla dışa aktarıldı",
            @"Settings export failed": @"Ayarlar dışa aktarılamadı",
            @"Export cancelled": @"Dışa aktarma iptal edildi",
            @"Import cancelled": @"İçe aktarma iptal edildi",
            @"Invalid settings file format": @"Geçersiz ayar dosyası biçimi",
            @"Settings imported successfully": @"Ayarlar başarıyla içe aktarıldı",
            @"GitHub": @"GitHub",
            @"Donate": @"Bağış yap",
            @"Version": @"Sürüm"
        };
    }

    if ([language hasPrefix:@"de"]) {
        return @{
            @"Block channel": @"Kanal blockieren",
            @"Block video": @"Video blockieren",
            @"Could not read the channel for this video": @"Kanal dieses Videos konnte nicht gelesen werden",
            @"Could not read a valid channel for this video": @"Kein gültiger Kanal für dieses Video gefunden",
            @"Blocked %@": @"%@ blockiert",
            @"Could not block this channel": @"Dieser Kanal konnte nicht blockiert werden",
            @"Could not read the video for this item": @"Video dieses Elements konnte nicht gelesen werden",
            @"Blocked video: %@": @"Video blockiert: %@",
            @"Could not block this video": @"Dieses Video konnte nicht blockiert werden",
            @"Filtering": @"Filterung",
            @"Blocked Content": @"Blockierte Inhalte",
            @"Settings": @"Einstellungen",
            @"Gonerino": @"Gonerino",
            @"Manage filtering, block lists, import/export, and support": @"Filterung, Blockierlisten, Import/Export und Unterstützung verwalten",
            @"About": @"Über",
            @"Enable Gonerino": @"Gonerino aktivieren",
            @"Show Gonerino Button": @"Gonerino-Schaltfläche anzeigen",
            @"Block 'People also watched'": @"„Auch angesehene Videos“ blockieren",
            @"Block 'You might also like'": @"„Das könnte dir auch gefallen“ blockieren",
            @"Remove blocked content from YouTube feeds": @"Blockierte Inhalte aus YouTube-Feeds entfernen",
            @"Display the quick toggle in the top navigation bar": @"Schnellumschalter in der oberen Navigationsleiste anzeigen",
            @"Remove this recommendation section": @"Diesen Empfehlungsbereich entfernen",
            @"Channels": @"Kanäle",
            @"Videos": @"Videos",
            @"Words": @"Wörter",
            @"blocked channel": @"blockierter Kanal",
            @"blocked channels": @"blockierte Kanäle",
            @"blocked video": @"blockiertes Video",
            @"blocked videos": @"blockierte Videos",
            @"blocked word": @"blockiertes Wort",
            @"blocked words": @"blockierte Wörter",
            @"Save your block lists and preferences": @"Blockierlisten und Einstellungen sichern",
            @"Restore your block lists and preferences": @"Blockierlisten und Einstellungen wiederherstellen",
            @"View source code and report issues": @"Quellcode ansehen und Probleme melden",
            @"Support Gonerino development": @"Gonerino-Entwicklung unterstützen",
            @"Blocked Channels": @"Blockierte Kanäle",
            @"Search channels": @"Kanäle durchsuchen",
            @"Add Channel": @"Kanal hinzufügen",
            @"Block a new channel": @"Einen neuen Kanal blockieren",
            @"Enter the channel name to block": @"Namen des zu blockierenden Kanals eingeben",
            @"Channel Name": @"Kanalname",
            @"Add": @"Hinzufügen",
            @"Cancel": @"Abbrechen",
            @"Delete Channel": @"Kanal löschen",
            @"Are you sure you want to delete '%@'?": @"„%@“ wirklich löschen?",
            @"Delete": @"Löschen",
            @"Blocked Videos": @"Blockierte Videos",
            @"Search videos": @"Videos durchsuchen",
            @"No blocked videos": @"Keine blockierten Videos",
            @"Unknown Channel": @"Unbekannter Kanal",
            @"Delete Video": @"Video löschen",
            @"Blocked Words": @"Blockierte Wörter",
            @"Search words": @"Wörter durchsuchen",
            @"Add Word": @"Wort hinzufügen",
            @"Block a new word or phrase": @"Ein neues Wort oder eine Phrase blockieren",
            @"Enter a word or phrase to block": @"Zu blockierendes Wort oder Phrase eingeben",
            @"Word or phrase": @"Wort oder Phrase",
            @"Delete Word": @"Wort löschen",
            @"Export Settings": @"Einstellungen exportieren",
            @"Import Settings": @"Einstellungen importieren",
            @"Could not create settings file": @"Einstellungsdatei konnte nicht erstellt werden",
            @"Settings exported successfully": @"Einstellungen erfolgreich exportiert",
            @"Settings export failed": @"Export der Einstellungen fehlgeschlagen",
            @"Export cancelled": @"Export abgebrochen",
            @"Import cancelled": @"Import abgebrochen",
            @"Invalid settings file format": @"Ungültiges Einstellungsdateiformat",
            @"Settings imported successfully": @"Einstellungen erfolgreich importiert",
            @"GitHub": @"GitHub",
            @"Donate": @"Spenden",
            @"Version": @"Version"
        };
    }

    if ([language hasPrefix:@"es"]) {
        return @{
            @"Block channel": @"Bloquear canal",
            @"Block video": @"Bloquear vídeo",
            @"Could not read the channel for this video": @"No se pudo leer el canal de este vídeo",
            @"Could not read a valid channel for this video": @"No se encontró un canal válido para este vídeo",
            @"Blocked %@": @"%@ bloqueado",
            @"Could not block this channel": @"No se pudo bloquear este canal",
            @"Could not read the video for this item": @"No se pudo leer el vídeo de este elemento",
            @"Blocked video: %@": @"Vídeo bloqueado: %@",
            @"Could not block this video": @"No se pudo bloquear este vídeo",
            @"Filtering": @"Filtrado",
            @"Blocked Content": @"Contenido bloqueado",
            @"Settings": @"Ajustes",
            @"Gonerino": @"Gonerino",
            @"Manage filtering, block lists, import/export, and support": @"Gestionar filtros, listas de bloqueo, importación/exportación y soporte",
            @"About": @"Acerca de",
            @"Enable Gonerino": @"Activar Gonerino",
            @"Show Gonerino Button": @"Mostrar botón de Gonerino",
            @"Block 'People also watched'": @"Bloquear «También se ha visto»",
            @"Block 'You might also like'": @"Bloquear «También te puede gustar»",
            @"Remove blocked content from YouTube feeds": @"Eliminar contenido bloqueado de los feeds de YouTube",
            @"Display the quick toggle in the top navigation bar": @"Mostrar el acceso rápido en la barra de navegación superior",
            @"Remove this recommendation section": @"Eliminar esta sección de recomendaciones",
            @"Channels": @"Canales",
            @"Videos": @"Vídeos",
            @"Words": @"Palabras",
            @"blocked channel": @"canal bloqueado",
            @"blocked channels": @"canales bloqueados",
            @"blocked video": @"vídeo bloqueado",
            @"blocked videos": @"vídeos bloqueados",
            @"blocked word": @"palabra bloqueada",
            @"blocked words": @"palabras bloqueadas",
            @"Save your block lists and preferences": @"Guardar listas de bloqueo y preferencias",
            @"Restore your block lists and preferences": @"Restaurar listas de bloqueo y preferencias",
            @"View source code and report issues": @"Ver código fuente e informar de problemas",
            @"Support Gonerino development": @"Apoyar el desarrollo de Gonerino",
            @"Blocked Channels": @"Canales bloqueados",
            @"Search channels": @"Buscar canales",
            @"Add Channel": @"Añadir canal",
            @"Block a new channel": @"Bloquear un canal nuevo",
            @"Enter the channel name to block": @"Introduce el nombre del canal que quieres bloquear",
            @"Channel Name": @"Nombre del canal",
            @"Add": @"Añadir",
            @"Cancel": @"Cancelar",
            @"Delete Channel": @"Eliminar canal",
            @"Are you sure you want to delete '%@'?": @"¿Seguro que quieres eliminar «%@»?",
            @"Delete": @"Eliminar",
            @"Blocked Videos": @"Vídeos bloqueados",
            @"Search videos": @"Buscar vídeos",
            @"No blocked videos": @"No hay vídeos bloqueados",
            @"Unknown Channel": @"Canal desconocido",
            @"Delete Video": @"Eliminar vídeo",
            @"Blocked Words": @"Palabras bloqueadas",
            @"Search words": @"Buscar palabras",
            @"Add Word": @"Añadir palabra",
            @"Block a new word or phrase": @"Bloquear una palabra o frase nueva",
            @"Enter a word or phrase to block": @"Introduce la palabra o frase que quieres bloquear",
            @"Word or phrase": @"Palabra o frase",
            @"Delete Word": @"Eliminar palabra",
            @"Export Settings": @"Exportar ajustes",
            @"Import Settings": @"Importar ajustes",
            @"Could not create settings file": @"No se pudo crear el archivo de ajustes",
            @"Settings exported successfully": @"Ajustes exportados correctamente",
            @"Settings export failed": @"No se pudieron exportar los ajustes",
            @"Export cancelled": @"Exportación cancelada",
            @"Import cancelled": @"Importación cancelada",
            @"Invalid settings file format": @"Formato de archivo de ajustes no válido",
            @"Settings imported successfully": @"Ajustes importados correctamente",
            @"GitHub": @"GitHub",
            @"Donate": @"Donar",
            @"Version": @"Versión"
        };
    }

    return @{};
}

NSString *LocalizedString(NSString *key) {
    if (key.length == 0)
        return key;

    NSString *language = [NSLocale preferredLanguages].firstObject.lowercaseString ?: @"";
    NSString *translation = TranslationsForLanguage(language)[key];
    return translation.length > 0 ? translation : key;
}

NSString *LocalizedCount(NSString *singular, NSString *plural, NSUInteger count) {
    NSString *label = LocalizedString(count == 1 ? singular : plural);
    return [NSString stringWithFormat:@"%lu %@", (unsigned long)count, label];
}
